version: '2.2'
services:
  api:
    container_name: api
    image: webapigo
    ports:
      - 8080:8080
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27100:27017
    healthcheck:
      test: echo 'db.stats().ok' | mongo mongo:27017 --quiet
      interval: 10s
      timeout: 25s
      retries: 1
    command: mongod --smallfiles